definitions:
  environment_versions: &sample_environment_versions
    xcode: 13.3
    vars:
      XCODE_PROJECT: "RaysLibrary.xcodeproj"
      XCODE_iOS_SCHEME: "RaysLibrary"
  scripts:
    - &check_architecture
      name: Check Architecture 
      script: ruby README.rb
    - &run_ios_tests
      name: Run iOS UI and Unit tests
      script: |
        xcode-project run-tests \
          --project "$XCODE_PROJECT" \
          --scheme "$XCODE_iOS_SCHEME" \
          --device "iPhone 12"
      test_report: build/ios/test/*.xml

workflows:
  ios-intel-testing-workflow:
    name: iOS Intel Testing Workflow
    instance_type: mac_mini
    environment:
      <<: *sample_environment_versions
    triggering:
      events:
        - push
    scripts:
      - which brew
      - which ruby 
      - which pod
      - *run_ios_tests
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/**/*.xcresult
  ios-m1-testing-workflow:
    name: iOS M1 Testing Workflow
    instance_type: mac_mini_m1
    environment:
      <<: *sample_environment_versions
    triggering:
      events:
        - push
    scripts:
     - which brew
     - which ruby 
     - which pod
     - if [ $(/usr/bin/pgrep oahd >/dev/null 2>&1;echo $?) -eq 0 ]; then echo 'rosetta installed'; fi
     - *check_architecture
     - name: Run iOS UI and Unit tests
       script: |
        arch -arm64 xcode-project run-tests \
          --project "$XCODE_PROJECT" \
          --scheme "$XCODE_iOS_SCHEME" \
          --device "iPhone 12"
       test_report: build/ios/test/*.xml
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/**/*.xcresult
